/* A deliberately small virtual shell. It does not execute operating-system commands. */
'use strict';
const terminalMissions=[
  {title:'Find where you are',body:'The working directory is the folder a relative path starts from. Ask the shell to print it.',hint:'pwd',test:m=>m.last.command==='pwd'},
  {title:'Look before you move',body:'List the contents of your home folder. The trailing / marks a folder in this trainer.',hint:'ls',test:m=>m.last.command==='ls'&&m.cwd==='/home/learner'},
  {title:'Enter the robot workspace',body:'Move into the robot_ws folder. The prompt changes with your working directory.',hint:'cd robot_ws',test:m=>m.cwd==='/home/learner/robot_ws'},
  {title:'Make somewhere for recordings',body:'Create a folder named logs inside robot_ws. mkdir creates a directory; it does not enter it.',hint:'mkdir logs',test:m=>m.nodes['/home/learner/robot_ws/logs']?.type==='dir'},
  {title:'Write your first file',body:'Use printf and > to create logs/session.txt containing mode=simulation followed by a newline. > replaces a file; >> appends.',hint:"printf 'mode=simulation\\n' > logs/session.txt",test:m=>m.nodes['/home/learner/robot_ws/logs/session.txt']?.content==='mode=simulation\n'},
  {title:'Read what you wrote',body:'Read logs/session.txt back. A command finishing without an error is useful; inspecting the result is better.',hint:'cat logs/session.txt',test:m=>m.last.command==='cat'&&m.last.output==='mode=simulation\n'},
  {title:'Keep a second copy',body:'Copy logs/session.txt to logs/session-backup.txt. cp preserves the original file.',hint:'cp logs/session.txt logs/session-backup.txt',test:m=>m.nodes['/home/learner/robot_ws/logs/session-backup.txt']?.content==='mode=simulation\n'},
  {title:'Find a warning in a log',body:'The sample telemetry.csv is already in robot_ws. Print only lines containing WARN. Matching is case sensitive.',hint:'grep WARN telemetry.csv',test:m=>m.last.command==='grep'&&m.last.output==='2,0.090,WARN\n'},
  {title:'Pass one command into another',body:'Pipe the warning lines into wc -l to count them. A pipe carries text from one command to the next.',hint:'grep WARN telemetry.csv | wc -l',test:m=>m.last.pipeline&&m.last.command==='wc'&&m.last.output.trim()==='1'},
  {title:'Save the result of an inspection',body:'Write the last two lines of telemetry.csv to logs/tail.csv. Read it afterward if you want to check the result.',hint:'tail -n 2 telemetry.csv > logs/tail.csv',test:m=>m.nodes['/home/learner/robot_ws/logs/tail.csv']?.content==='2,0.090,WARN\n3,0.005,OK\n'},
  {title:'Rename without losing data',body:'Rename logs/tail.csv to logs/recent.csv with mv. Verify it using ls logs.',hint:'mv logs/tail.csv logs/recent.csv',test:m=>!m.nodes['/home/learner/robot_ws/logs/tail.csv']&&m.nodes['/home/learner/robot_ws/logs/recent.csv']?.content==='2,0.090,WARN\n3,0.005,OK\n'},
  {title:'Return home',body:'cd with no path returns to your home directory. Your files remain in robot_ws/logs.',hint:'cd',test:m=>m.cwd==='/home/learner'&&m.last.command==='cd'}
];
function newTerminalModel(){return {cwd:'/home/learner',nodes:{'/':{type:'dir'},'/home':{type:'dir'},'/home/learner':{type:'dir'},'/home/learner/robot_ws':{type:'dir'},'/home/learner/robot_ws/src':{type:'dir'},'/home/learner/robot_ws/README.txt':{type:'file',content:'Robot workspace\nKeep code in src and measurements in logs.\n'},'/home/learner/robot_ws/telemetry.csv':{type:'file',content:'sample,age_s,status\n1,0.004,OK\n2,0.090,WARN\n3,0.005,OK\n'}},mission:0,history:[],transcript:[],last:{command:'',output:'',pipeline:false}}}
function terminalPath(m,p){p=p==='~'?'/home/learner':p.startsWith('~/')?'/home/learner/'+p.slice(2):p;const out=[];for(const bit of(p.startsWith('/')?p:m.cwd+'/'+p).split('/')){if(bit==='..')out.pop();else if(bit&&bit!=='.')out.push(bit)}return '/'+out.join('/')}
function shellTokens(s){const tokens=[];let value='',quote='',started=false;const push=()=>{if(started){tokens.push({value,operator:false});value='';started=false}};for(let i=0;i<s.length;i++){const c=s[i];if(quote){if(c===quote)quote='';else value+=c;continue}if(c==="'"||c==='"'){quote=c;started=true}else if(/\s/.test(c))push();else if(c==='|'||c==='>'){push();let op=c;if(c==='>'&&s[i+1]==='>'){op='>>';i++}tokens.push({value:op,operator:true})}else if(c===';'||c==='&'||c==='<'||c==='`'||c==='$'){throw Error('This trainer supports one command or pipeline per line. Use the commands in help; shell expansion is not implemented.')}else{value+=c;started=true}}if(quote)throw Error('The quote is not closed. Add the matching quote and try again.');push();return tokens}
function terminalRun(m,line){
  const original=line.trim();if(!original)return '';
  let output='';m.history.push(original);m.last={command:'',output:'',pipeline:false};
  try{
    const tokens=shellTokens(original),chunks=[[]];let dest=null,append=false;
    for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t.operator&&t.value==='|'){if(!chunks.at(-1).length)throw Error('A pipe needs a command on both sides.');chunks.push([])}else if(t.operator&&t.value.startsWith('>')){if(i!==tokens.length-2||tokens[i+1]?.operator)throw Error('Put one output file at the end of the command.');dest=terminalPath(m,tokens[i+1].value);append=t.value==='>>';break}else chunks.at(-1).push(t.value)}
    if(!chunks.at(-1).length)throw Error('The command is missing.');
    if(dest){if(m.nodes[dest]?.type==='dir')throw Error('The output path is a directory. Choose a file name.');if(m.nodes[dest.slice(0,dest.lastIndexOf('/'))||'/']?.type!=='dir')throw Error('The output folder does not exist. Create it with mkdir first.')}
    let input=null;
    const read=p=>{const n=m.nodes[terminalPath(m,p)];if(!n)throw Error('No such file: '+p);if(n.type!=='file')throw Error(p+' is a directory.');return n.content};
    const write=(p,data)=>{const path=terminalPath(m,p),parent=path.slice(0,path.lastIndexOf('/'))||'/';if(m.nodes[parent]?.type!=='dir')throw Error('The destination folder does not exist.');if(m.nodes[path]?.type==='dir')throw Error('Name an output file, not a directory.');m.nodes[path]={type:'file',content:data};return path};
    for(const words of chunks){const [cmd,...args]=words;m.last.command=cmd;output='';switch(cmd){
      case 'help':output='Supported: pwd, ls [path], cd [path], mkdir [-p] path, printf TEXT, echo TEXT, cat file, cp source destination, mv source destination, grep TEXT [file], wc -l [file], tail -n N [file], clear, help.\nOperators: |, >, >>. Quotes preserve spaces. This is a teaching simulation, not a full Bash shell.\n';break;
      case 'pwd':if(args.length)throw Error('pwd takes no arguments in this trainer.');output=m.cwd+'\n';break;
      case 'ls':{if(args.length>1||args[0]?.startsWith('-'))throw Error('Use ls or ls path in this trainer.');const path=terminalPath(m,args[0]||'.');if(!m.nodes[path])throw Error('No such directory: '+(args[0]||'.'));if(m.nodes[path].type==='file'){output=path.split('/').pop()+'\n';break}const prefix=path==='/'?'/':path+'/';output=Object.keys(m.nodes).filter(p=>p.startsWith(prefix)&&!p.slice(prefix.length).includes('/')&&p!==path).sort().map(p=>p.slice(prefix.length)+(m.nodes[p].type==='dir'?'/':'')).join('  ')+'\n';break}
      case 'cd':{if(args.length>1)throw Error('cd takes one path.');const path=terminalPath(m,args[0]||'/home/learner');if(m.nodes[path]?.type!=='dir')throw Error('No such directory: '+(args[0]||''));m.cwd=path;break}
      case 'mkdir':{const recursive=args[0]==='-p',paths=recursive?args.slice(1):args;if(paths.length!==1)throw Error('Use mkdir path or mkdir -p path.');const path=terminalPath(m,paths[0]);if(m.nodes[path]){if(recursive&&m.nodes[path].type==='dir')break;throw Error('A file or directory already exists at '+paths[0])}const parts=path.split('/').filter(Boolean);let current='';for(let i=0;i<parts.length;i++){current+='/'+parts[i];if(m.nodes[current]?.type==='file')throw Error('A parent path is a file.');if(!m.nodes[current]){if(!recursive&&i!==parts.length-1)throw Error('Parent folder missing. Use mkdir -p to create parents.');m.nodes[current]={type:'dir'}}}break}
      case 'printf':if(args.length!==1)throw Error("Use printf 'text\\n' in this trainer. Format substitutions are not implemented.");output=args[0].replace(/\\n/g,'\n').replace(/\\t/g,'\t').replace(/\\\\/g,'\\');break;
      case 'echo':output=args.join(' ')+'\n';break;
      case 'cat':if(args.length!==1)throw Error('Use cat file.');output=read(args[0]);break;
      case 'cp':case 'mv':{if(args.length!==2)throw Error(cmd+' needs a source file and destination file.');const src=terminalPath(m,args[0]),dst=terminalPath(m,args[1]);if(src===dst)throw Error('Source and destination are the same file.');write(args[1],read(args[0]));if(cmd==='mv')delete m.nodes[src];break}
      case 'grep':{if(!args.length||args.length>2)throw Error('Use grep TEXT file, or pipe into grep TEXT.');const data=args[1]?read(args[1]):input;if(data===null)throw Error('Provide a file or pipe text into grep.');const lines=data.split('\n');if(lines.at(-1)==='')lines.pop();const matches=lines.filter(l=>l.includes(args[0]));output=matches.length?matches.join('\n')+'\n':'';break}
      case 'wc':{if(args[0]!=='-l'||args.length>2)throw Error('This trainer supports wc -l [file].');const data=args[1]?read(args[1]):input;if(data===null)throw Error('Provide a file or pipe text into wc -l.');output=String((data.match(/\n/g)||[]).length)+'\n';break}
      case 'tail':{if(args[0]!=='-n'||!/^\d+$/.test(args[1]||'')||args.length>3)throw Error('Use tail -n N [file].');const data=args[2]?read(args[2]):input;if(data===null)throw Error('Provide a file or pipe text into tail.');const newline=data.endsWith('\n'),lines=data.split('\n');if(newline)lines.pop();const count=+args[1];output=count?lines.slice(-count).join('\n')+(newline&&lines.length?'\n':''):'';break}
      case 'clear':if(chunks.length!==1||dest)throw Error('Use clear by itself.');m.transcript=[];break;
      default:throw Error(cmd==='sudo'||cmd==='ssh'||cmd==='apt'?'This is a virtual practice shell. It cannot install software or contact a computer. Use the Linux course for real terminal commands.':'Command not supported: '+cmd+'. Type help for the supported set.');
    }input=output}
    m.last={command:m.last.command,output,pipeline:chunks.length>1};
    if(dest){m.nodes[dest]={type:'file',content:(append?m.nodes[dest]?.content||'':'')+output};output=''}
    if(m.mission<terminalMissions.length&&terminalMissions[m.mission].test(m)){m.mission++;output+='\n✓ Exercise complete. '+(m.mission<terminalMissions.length?'Next: '+terminalMissions[m.mission].title+'\n'+terminalMissions[m.mission].body:'You completed all 12 tasks. Continue in a real Linux terminal.')+'\n'}
  }catch(e){output='trainer: '+e.message+'\n';m.last={command:'error',output,pipeline:false}}
  return output;
}
let terminalModel=newTerminalModel();
function terminalPage(){return head('LINUX PRACTICE','Your first terminal session.','Practice file navigation and text commands before opening a real Linux terminal.')+`<div class="terminal-layout"><section class="panel terminal-task" id="terminal-task"></section><section class="terminal-shell" aria-label="Virtual terminal"><div class="terminal-title"><span><i></i> learner@academy</span><span>Browser simulation · no computer access</span></div><div class="terminal-output" id="terminal-output" role="log" aria-live="polite"></div><form id="terminal-form" class="terminal-command"><label for="terminal-input" id="terminal-prompt"></label><input id="terminal-input" spellcheck="false" autocomplete="off" autocapitalize="off" aria-label="Terminal command"><button type="submit">Run</button></form></section><div class="terminal-help panel"><h2>How this practice works</h2><p>Type a command and press Enter. Use the up and down arrow keys to recall commands. File names are case sensitive. All files here are simulated in this tab; reloading starts over.</p><p>The trainer implements only the commands listed by <code>help</code>, with limited flags. It does not run Bash, connect to robots, or install packages.</p><div class="actions"><button class="button" id="terminal-reset">Reset practice</button><a class="button primary" href="#/course/linux-from-zero">Open the Linux course</a><a class="button" href="#/code">Get real programs</a></div></div></div>`}
function updateTerminal(){const m=terminalModel,mission=terminalMissions[m.mission];$('#terminal-task').innerHTML=mission?`<p class="eyebrow">EXERCISE ${m.mission+1} / ${terminalMissions.length}</p><h2>${esc(mission.title)}</h2><p>${esc(mission.body)}</p><details class="terminal-hint"><summary>Show the command</summary><code>${esc(mission.hint)}</code></details><div class="progress-track"><span style="width:${m.mission/terminalMissions.length*100}%"></span></div>`:`<p class="eyebrow">12 / 12 COMPLETE</p><h2>You can navigate, write, and inspect.</h2><p>These commands use the same spelling in a real Bash terminal. Continue with the Linux course to learn permissions, processes, packages, SSH, and Git.</p><a class="button primary" href="#/course/linux-from-zero">Continue learning</a>`;$('#terminal-prompt').textContent='learner:'+m.cwd.replace('/home/learner','~')+' $';const out=$('#terminal-output');out.textContent=m.transcript.length?m.transcript.join('\n'):'Robotics Academy terminal trainer\nType help to see the supported commands.\nComplete the task above to begin.\n';out.scrollTop=out.scrollHeight}
function bindTerminal(){if(!$('#terminal-form'))return;updateTerminal();let historyIndex=terminalModel.history.length;$('#terminal-form').onsubmit=e=>{e.preventDefault();const input=$('#terminal-input'),line=input.value;if(!line.trim())return;const prompt='learner:'+terminalModel.cwd.replace('/home/learner','~')+' $ '+line;const output=terminalRun(terminalModel,line);if(line.trim()!=='clear')terminalModel.transcript.push(prompt,output);input.value='';historyIndex=terminalModel.history.length;updateTerminal();input.focus()};$('#terminal-input').onkeydown=e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.max(0,Math.min(terminalModel.history.length,historyIndex+(e.key==='ArrowUp'?-1:1)));e.target.value=terminalModel.history[historyIndex]||''}};$('#terminal-reset').onclick=()=>{terminalModel=newTerminalModel();historyIndex=0;updateTerminal();$('#terminal-input').value='';$('#terminal-input').focus()}}
